//created on: 7/10/2018
package org.drools.tutorial.rules

//list any import classes here.
import org.drools.tutorial.model.Item;
import org.drools.tutorial.model.Person;
//import org.drools.tutorial.model.Order;
import java.math.BigDecimal;

//declare any global variables here
global java.util.List points;

declare Order
  value : BigDecimal @key
  tieneImpuesto: boolean
end

rule "sum order"
    //include attributes such as "salience" here...
    agenda-group "init-sum"
    when
    	not Order()
        $total: BigDecimal() from 
        	accumulate(Item($price: price, $amout: amount ), sum($price.multiply(new BigDecimal($amout))))
    then
		System.out.println("precio total de la compra: " + $total);
		insert(new Order($total));
end

rule "calcular impuesto"
    //include attributes such as "salience" here...
    agenda-group "init-sum"
    no-loop true
    when
        $order: Order()
    then
		$order.setValue($order.getValue().multiply(new BigDecimal("1.19")));
		System.out.println("precio con impuesto: " + $order.getValue());
		$order.setTieneImpuesto(true);
		update($order);
end

rule "points by amount"
    //include attributes such as "salience" here...
    auto-focus true
    when
        Item($amount: amount >= 20L)
    then
		System.out.println("puntos por cantidad: " + 5L*($amount/20L));
		points.add(5L*($amount/20L));
end

rule "points by price order"
    when
        Order( $value: value, tieneImpuesto == true)
    then
		System.out.println("puntos por precio: " + $value.divide(new BigDecimal("10000")).longValue());
        points.add($value.divide(new BigDecimal("10000")).longValue());
end

rule "points by price item"
    auto-focus true
    when
        Item( price >= 500000L, $amount: amount )
    then
		System.out.println("puntos por precio item: " + 10L*$amount);
		points.add(10L*$amount);
end

rule "miles by points"
	no-loop true
    when
        $person: Person($points : points)
    then
    	System.out.println("Millas por puntos: " + $points);
    	modify ($person) {
    		setMiles($points)
    	}
end

rule "verify date registry"
    when
        $person: Person(miles > 0)
        //validar fecha de registro
    then
		System.out.println("Persona con millas: " + $person.getMiles());
end


